"""HTTP guards for business operations that must not bypass audited workflows."""

from __future__ import annotations

import re

from fastapi import Request
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.config_production import prod_settings
from app.database import SessionLocal
from app.models import Product, StockHistory


_PRODUCT_STOCK_PATHS = (
    re.compile(r"^/api/products/(?P<product_id>\d+)/stock$"),
    re.compile(r"^/api/products/(?P<product_id>\d+)/stock/location/\d+$"),
)
_PRODUCT_DELETE_PATH = re.compile(r"^/api/products/(?P<product_id>\d+)$")
_META_WEBHOOK_PATH = re.compile(r"^/api/channels/(whatsapp|messenger|instagram)/webhook$")


class BusinessIntegrityMiddleware(BaseHTTPMiddleware):
    """Block unsafe shortcuts before they reach otherwise-valid router code."""

    async def dispatch(self, request: Request, call_next):
        path = request.url.path.rstrip("/") or "/"

        # StockHistory is evidence generated by real stock operations. Allowing a
        # caller to append arbitrary rows makes the audit trail untrustworthy.
        if request.method == "POST" and path == "/api/stock-history":
            return JSONResponse(
                status_code=405,
                content={
                    "detail": (
                        "El historial de stock es de solo lectura. Use recepción de compra, "
                        "conteo físico, venta, devolución, transferencia o ajuste Super Admin auditado."
                    )
                },
            )

        # A numeric-only adjustment cannot safely alter a serialized product because
        # there is no IMEI payload to reconcile. Physical count/restock are IMEI-aware.
        for pattern in _PRODUCT_STOCK_PATHS:
            match = pattern.match(path)
            if match and request.method in {"POST", "PUT"}:
                with SessionLocal() as db:
                    product = db.query(Product).filter(Product.id == int(match.group("product_id"))).first()
                    if product and product.is_serialized:
                        return JSONResponse(
                            status_code=409,
                            content={
                                "detail": (
                                    "Los productos serializados no admiten ajustes numéricos directos. "
                                    "Use reabastecimiento con IMEIs o un conteo físico para reconciliar stock e IMEIs."
                                )
                            },
                        )

        # Ordinary DELETE must never erase an inventory movement trail. Products with
        # operational history are deactivated; the separately guarded Super Admin purge
        # remains the explicit disaster/correction path.
        if request.method == "DELETE":
            match = _PRODUCT_DELETE_PATH.match(path)
            if match:
                product_id = int(match.group("product_id"))
                with SessionLocal() as db:
                    movement_exists = (
                        db.query(StockHistory.id)
                        .filter(StockHistory.product_id == product_id)
                        .first()
                    )
                    if movement_exists:
                        return JSONResponse(
                            status_code=409,
                            content={
                                "detail": (
                                    "No se puede eliminar un producto con historial de movimientos. "
                                    "Desactívelo con activo=false para conservar la trazabilidad."
                                )
                            },
                        )

        if prod_settings.is_production():
            # Service-originated photo requests must fail closed in production when
            # the shared integration token was never configured. Authenticated staff
            # requests continue to the normal router permission checks.
            if request.method == "POST" and path == "/api/photo-requests":
                has_user_auth = bool(request.headers.get("Authorization"))
                if not has_user_auth and not (prod_settings.N8N_AUTH_TOKEN or "").strip():
                    return JSONResponse(
                        status_code=503,
                        content={
                            "detail": "Integración de solicitudes de fotos no configurada: falta N8N_AUTH_TOKEN"
                        },
                    )

            # Meta POST webhooks must never be processed unsigned in production.
            if request.method == "POST" and _META_WEBHOOK_PATH.match(path):
                if not (getattr(prod_settings, "META_APP_SECRET", "") or "").strip():
                    return JSONResponse(
                        status_code=503,
                        content={
                            "detail": "Webhook Meta bloqueado: META_APP_SECRET no está configurado"
                        },
                    )

        return await call_next(request)
