"""HTTP guards for business operations that must not bypass audited workflows."""

from __future__ import annotations

import re

import jwt
from jwt import PyJWTError as JWTError
from fastapi import Request
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.config import settings
from app.config_production import prod_settings
from app.database import SessionLocal
from app.models import Product, StockHistory, User


_PRODUCT_STOCK_PATHS = (
    re.compile(r"^/api/products/(?P<product_id>\d+)/stock$"),
    re.compile(r"^/api/products/(?P<product_id>\d+)/stock/location/\d+$"),
)
_PRODUCT_DELETE_PATH = re.compile(r"^/api/products/(?P<product_id>\d+)$")
_META_WEBHOOK_PATH = re.compile(r"^/api/channels/(whatsapp|messenger|instagram)/webhook$")
_PHOTO_REQUEST_CREATE_PATH = "/api/photo-requests/create"


def _has_active_bearer_user(request: Request) -> bool:
    """Validate the Bearer JWT and active user before treating it as staff auth."""
    authorization = (request.headers.get("Authorization") or "").strip()
    if not authorization.lower().startswith("bearer "):
        return False

    token = authorization[7:].strip()
    if not token:
        return False

    try:
        payload = jwt.decode(token, settings.secret_key, algorithms=[settings.algorithm])
    except JWTError:
        return False

    username = payload.get("sub")
    if not username:
        return False

    with SessionLocal() as db:
        user = (
            db.query(User.id)
            .filter(User.username == str(username), User.is_active == True)
            .first()
        )
    return user is not None


class BusinessIntegrityMiddleware(BaseHTTPMiddleware):
    """Block unsafe shortcuts before they reach otherwise-valid router code."""

    async def dispatch(self, request: Request, call_next):
        path = request.url.path.rstrip("/") or "/"

        # StockHistory is evidence generated by real stock operations. Allowing a
        # caller to append arbitrary rows makes the audit trail untrustworthy.
        if request.method == "POST" and path == "/api/stock-history":
            return JSONResponse(
                status_code=405,
                content={
                    "detail": (
                        "El historial de stock es de solo lectura. Use recepción de compra, "
                        "conteo físico, venta, devolución, transferencia o ajuste Super Admin auditado."
                    )
                },
            )

        # A numeric-only adjustment cannot safely alter a serialized product because
        # there is no IMEI payload to reconcile. Physical count/restock are IMEI-aware.
        for pattern in _PRODUCT_STOCK_PATHS:
            match = pattern.match(path)
            if match and request.method in {"POST", "PUT"}:
                with SessionLocal() as db:
                    product = db.query(Product).filter(Product.id == int(match.group("product_id"))).first()
                    if product and product.is_serialized:
                        return JSONResponse(
                            status_code=409,
                            content={
                                "detail": (
                                    "Los productos serializados no admiten ajustes numéricos directos. "
                                    "Use reabastecimiento con IMEIs o un conteo físico para reconciliar stock e IMEIs."
                                )
                            },
                        )

        # Ordinary DELETE must never erase an inventory movement trail. Products with
        # operational history are deactivated; the separately guarded Super Admin purge
        # remains the explicit disaster/correction path.
        if request.method == "DELETE":
            match = _PRODUCT_DELETE_PATH.match(path)
            if match:
                product_id = int(match.group("product_id"))
                with SessionLocal() as db:
                    movement_exists = (
                        db.query(StockHistory.id)
                        .filter(StockHistory.product_id == product_id)
                        .first()
                    )
                    if movement_exists:
                        return JSONResponse(
                            status_code=409,
                            content={
                                "detail": (
                                    "No se puede eliminar un producto con historial de movimientos. "
                                    "Desactívelo con activo=false para conservar la trazabilidad."
                                )
                            },
                        )

        if prod_settings.is_production():
            # Service-originated photo requests must fail closed in production when
            # the shared integration token was never configured. Only a verified,
            # active JWT user may bypass that missing-service-token guard.
            if request.method == "POST" and path == _PHOTO_REQUEST_CREATE_PATH:
                has_verified_user = _has_active_bearer_user(request)
                if not has_verified_user and not (prod_settings.N8N_AUTH_TOKEN or "").strip():
                    return JSONResponse(
                        status_code=503,
                        content={
                            "detail": "Integración de solicitudes de fotos no configurada: falta N8N_AUTH_TOKEN"
                        },
                    )

            # Meta POST webhooks must never be processed unsigned in production.
            if request.method == "POST" and _META_WEBHOOK_PATH.match(path):
                if not (getattr(prod_settings, "META_APP_SECRET", "") or "").strip():
                    return JSONResponse(
                        status_code=503,
                        content={
                            "detail": "Webhook Meta bloqueado: META_APP_SECRET no está configurado"
                        },
                    )

        return await call_next(request)
