import { beforeEach, describe, expect, it } from 'vitest'

import { exportAllData, importAllData } from '../dataInitializer'
import { getKV, resetKV } from '../kvStorage'


describe('browser upgrade backups', () => {
  beforeEach(() => {
    localStorage.clear()
    resetKV()
  })

  it('exports every KV key instead of only the original V1 collections', async () => {
    const kv = getKV()
    await kv.set('inventory-products', [{ id: 1, nombre: 'iPhone' }])
    await kv.set('inventory-product-imeis', [{ id: 9, imei: '123456789012345' }])
    await kv.set('inventory-stock-transfers', [{ id: 3, cantidad: 2 }])
    await kv.set('inventory-customers', [{ id: 4, phone: '99990000' }])
    await kv.set('future-upgrade-key', { preserved: true })

    const backup = await exportAllData()

    expect(backup.format).toBe('softmobile-browser-backup')
    expect(backup.formatVersion).toBe(3)
    expect(backup.products).toEqual([{ id: 1, nombre: 'iPhone' }])
    expect(backup.kv?.['inventory-product-imeis']).toEqual([
      { id: 9, imei: '123456789012345' }
    ])
    expect(backup.kv?.['inventory-stock-transfers']).toEqual([
      { id: 3, cantidad: 2 }
    ])
    expect(backup.kv?.['inventory-customers']).toEqual([
      { id: 4, phone: '99990000' }
    ])
    expect(backup.kv?.['future-upgrade-key']).toEqual({ preserved: true })
  })

  it('restores a complete V3 snapshot including keys unknown to older versions', async () => {
    await importAllData({
      format: 'softmobile-browser-backup',
      formatVersion: 3,
      kv: {
        'inventory-orders': [{ id: 10, total: 1000 }],
        'inventory-imei-history': [{ id: 11, imei: 'ABC' }],
        'future-upgrade-key': ['kept']
      }
    })

    const kv = getKV()
    expect(await kv.get('inventory-orders')).toEqual([{ id: 10, total: 1000 }])
    expect(await kv.get('inventory-imei-history')).toEqual([{ id: 11, imei: 'ABC' }])
    expect(await kv.get('future-upgrade-key')).toEqual(['kept'])
  })

  it('still imports backups generated by the old five-collection format', async () => {
    await importAllData({
      profiles: [{ id: 1 }],
      products: [{ id: 2 }],
      stock: [{ product_id: 2, cantidad: 5 }],
      orders: [{ id: 3 }],
      orderItems: [{ id: 4, order_id: 3 }]
    })

    const kv = getKV()
    expect(await kv.get('inventory-profiles')).toEqual([{ id: 1 }])
    expect(await kv.get('inventory-products')).toEqual([{ id: 2 }])
    expect(await kv.get('inventory-stock')).toEqual([{ product_id: 2, cantidad: 5 }])
    expect(await kv.get('inventory-orders')).toEqual([{ id: 3 }])
    expect(await kv.get('inventory-order-items')).toEqual([{ id: 4, order_id: 3 }])
  })
})
